services:
  postgres:
    container_name: mockio-postgres-local
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${AUTH_DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/postgresql/data
    restart: always

    # ğŸ”¹ Postgresê°€ ì§„ì§œ ì ‘ì† ê°€ëŠ¥í•œ ìƒíƒœì¸ì§€ í—¬ìŠ¤ì²´í¬
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 5s       # 5ì´ˆë§ˆë‹¤ ì²´í¬
      timeout: 5s
      retries: 10        # ìµœëŒ€ 10ë²ˆ ì‹œë„
      start_period: 10s  # ì²˜ìŒ 10ì´ˆëŠ” ì›Œë°ì—… ì‹œê°„

  keycloak:
    container_name: keycloak-local
    command: ["start-dev"]
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/${KEYCLOAK_DB_NAME}
      KC_DB_USERNAME: ${DB_USER}
      KC_DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8084:8080"
    volumes:
      - C:/project/mockio/keycloak-themes/mockio-theme:/opt/keycloak/themes/mockio-theme
    restart: always

    # ğŸ”¹ Postgresê°€ healthy ë˜ê¸° ì „ê¹Œì§€ëŠ” Keycloak ì‹œì‘ ì•ˆ í•¨
    depends_on:
      postgres:
        condition: service_healthy
