server:
  port: 9000

spring:
  profiles:
    active: local
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:9080
          predicates:
            - Path=/api/auth/v1/**
        - id: user-service
          uri: http://localhost:9081
          predicates:
            - Path=/api/users/v1/**
        - id: interview-service
          uri: http://localhost:9082
          predicates:
            - Path=/api/interview/v1/**
