server:
  port: 9000

spring:
  profiles:
    active: local
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:9080
          predicates:
            - Path=/api/auth/v1/**
        - id: user-service
          uri: http://localhost:9081
          predicates:
            - Path=/api/users/v1/**
        - id: interview-service
          uri: http://localhost:9082
          predicates:
            - Path=/api/interview/v1/**
        - id: feedback-service
          uri: http://localhost:9083
          predicates:
            - Path=/api/feedback/v1/**
        - id: noti-service
          uri: http://localhost:9084
          predicates:
            - Path=/api/noti/v1/**
        - id: inquiry-service
          uri: http://localhost:9085
          predicates:
            - Path=/api/inquiry/v1/**
        - id: faq-service
          uri: http://localhost:9086
          predicates:
            - Path=/api/faq/v1/**

