server:
  port: 9083

spring:
  messages:
    basename: messages/apiResponseMessage
    encoding: UTF-8
  profiles:
    active: local
  application:
    name: feedback-service

  datasource:
    url: jdbc:postgresql://localhost:5432/${USER_DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
  config:
    import: classpath:application-kafka.yaml

services:
  ai:
    base-url: http://localhost:9100

